name: mirageclient
description: "A photo and video library"
publish_to: 'none'
version: 2025.02.10

environment:
  sdk: ^3.6.2

# `flutter pub upgrade --major-versions`
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  filesize: ^2.0.1
  http: ^1.2.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  cached_network_image_platform_interface: ^4.1.1
  photo_view: ^0.15.0
  video_player: ^2.9.1
  file_saver: ^0.2.14
  package_info_plus: ^8.0.2
  google_fonts: ^6.2.1
  easy_sidemenu: ^0.6.0
  http_parser: ^4.0.2
  flutter_blurhash: ^0.8.2
  intl: ^0.19.0
  flutter_sticky_header: ^0.7.0
  flexible_scrollbar: ^0.1.3
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.1
  flutter_session_manager: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
