name: Publish Container

on:
  workflow_run:
    workflows: [Deploy Flutter Web]
    types: [completed]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: "production"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Dockerfile
        run: |
          cat <<EOF > Dockerfile
          FROM nginx:latest
          WORKDIR /usr/share/nginx/html
          RUN rm -f ./*
          COPY . .
          EXPOSE 80
          CMD ["nginx", "-g", "daemon off;"]
          EOF

      - name: Generate a random tag
        run: echo "TAG=$(openssl rand -hex 4)" >> $GITHUB_ENV

      - name: Build and push container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/hetkpatel/mirage-web:latest
            ghcr.io/hetkpatel/mirage-web:${{ env.TAG }}
